export const CONTENT_TYPES = {
  GET_CITIES: 'GET_CITIES',
  GET_CURRENT_WEATHER: 'GET_CURRENT_WEATHER',
  GET_FIVE_DAYS_FORECAST: 'GET_FIVE_DAYS_FORECAST',
  SET_CITIES: 'SET_CITIES',
  SET_CURRENT_WEATHER: 'SET_CURRENT_WEATHER',
  SET_FIVE_DAYS_FORECAST: 'SET_FIVE_DAYS_FORECAST',
  SET_IS_CITIES_LOADING: 'SET_IS_CITIES_LOADING',
  SET_IS_WEATHER_LOADING: 'SET_IS_WEATHER_LOADING',
  SET_LAST_CITY: 'SET_LAST_CITY',
  SET_REQUEST_ERROR: 'SET_REQUEST_ERROR',
};
